AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Severity: warning

Metrics/BlockLength:
  Severity: warning