extends: default

ignore:
  - config/locales/*.yml
  - vendor/**/*
  - db/**/*
  - bin/*
  - test/fixtures/active_storage/* # blob fixtures don't have proper yml syntax!

rules:
  line-length:
    max: 120

  document-start:
    present: false

  truthy:
    check-keys: false

  comments:
    min-spaces-from-content: 1
